apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: userprofile
        image: registryyaf2729.azurecr.io/tripinsights/userprofile:1.0
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: server
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
  labels:
    run: userprofile
spec:
  ports:
  - port: 80
  selector:
    app: userprofile
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: web
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: tripviewer1.edcdeaa83cd24437be0f.eastasia.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: tripviewer
            port: 
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: tripviewer1.edcdeaa83cd24437be0f.eastasia.aksapp.io
    http:
      paths:
      - path: /api/user
        pathType: Prefix
        backend:
          service: 
            name: userprofile
            port: 
              number: 80
      - path: /api/trips
        pathType: Prefix
        backend:
          service: 
            name: trips-service
            port: 
              number: 80
      - path: /api/poi
        pathType: Prefix
        backend:
          service: 
            name: poi
            port: 
              number: 80
      - path: /api/user-java
        pathType: Prefix
        backend:
          service: 
            name: user-java-service
            port: 
              number: 80